name = "m4a-to-notes"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "e2c1e0edd19dc5cd47f9acd256ba94ec"

compatibility_flags = ["nodejs_compat"]


[[kv_namespaces]]
binding = "CONVERSATIONS"
id = "37462871a7824d94985cbbdcdb4baf08"

[[kv_namespaces]]
binding = "JOBS"
id = "8837ef40371245b4ac1d70bbc81c9831"

[[r2_buckets]]
binding = "M4A_BUCKET"
bucket_name = "m4a-to-notes"

[[kv_namespaces]]
binding = "ENTITLEMENTS"
id = "342f8d83f226463796e72d7be214fe16"

[[queues.producers]]
binding = "QUEUE"
queue = "transcribe"

[[queues.consumers]]
queue = "transcribe"
max_batch_size = 5
max_batch_timeout = 5


# No cron triggers needed with canonical sync approach

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true





[vars]
NODE_ENV = "production"
LOG_LEVEL = "INFO"
# Non-sensitive R2 configuration
R2_ENDPOINT = "https://e2c1e0edd19dc5cd47f9acd256ba94ec.r2.cloudflarestorage.com"
R2_BUCKET_NAME = "m4a-to-notes"
R2_REGION = "auto"

# Secrets should be set using: npx wrangler secret put SECRET_NAME
# Required secrets:
# - TELEGRAM_BOT_TOKEN
# - OPENAI_API_KEY  
# - R2_ACCESS_KEY_ID
# - R2_SECRET_ACCESS_KEY
# - INTERNAL_API_SECRET
# - PADDLE_API_KEY (for subscription management)
# - PADDLE_ENVIRONMENT (sandbox or production)

