name = "m4a-to-notes"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"
LOG_LEVEL = "INFO"
TELEGRAM_BOT_TOKEN = "your_telegram_bot_token_here"
OPENAI_API_KEY = "your_openai_api_key_here"